name: clusek_tt
description: Flutter based DDS texture compression tool.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: 2.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  bloc: 8.0.1
  flutter_bloc: 8.0.0
  get_it: 7.2.0
  logger: 1.1.0
  intl: 0.17.0
  freezed_annotation: 1.0.0
  filepicker_windows: 2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: 1.0.2
  build_runner: 2.1.5
  flutter_lints: 1.0.4
  bloc_test: 9.0.1
  mockito: 5.0.16

flutter:
  generate: true
  uses-material-design: true
