name: clusek_tt
description: Flutter based DDS texture compression tool.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: 2.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 1.0.4

flutter:
  uses-material-design: true
